### ISSUE TITLE
CopyAssignment doesn't clean

### ISSUE THREAD

**Issue by okovtun** [StraAnger/DataConteiners#1]
Здравствуйте Антон! Вот здесь нужно очистить список так же как в деструкторе:
https://github.com/StraAnger/DataConteiners/blob/9c72dc27b727e4678e306c318adcce72f7b2e47f/ForwardList/Main.cpp#L212

**Comment by StraAnger** [comment]
Добрый вечер. Олег, понял, спасибо!
