### ISSUE TITLE
Shallow copy in CopyAssignment

### ISSUE THREAD

**Issue by okovtun** [StraAnger/DataConteiners#2]
Антон, конструктор копирования должен выполнять DeepCopy, а Ваш выполняет ShallowCopy:
https://github.com/StraAnger/DataConteiners/blob/9c72dc27b727e4678e306c318adcce72f7b2e47f/ForwardList/Main.cpp#L196

**Comment by StraAnger** [comment]
Спасибо, Олег! Да, я запутался немного. Спасибо!

**Comment by okovtun** [comment]
Не за что, Ю ар велкам))
